Add Azure Devops Pipelines for BP folder

diff --git a/pipeline/terraform.yml b/pipeline/terraform.yml
--- a/pipeline/terraform.yml
+++ b/pipeline/terraform.yml
@@ -1,72 +1,57 @@
-# Starter pipeline
-# Start with a minimal pipeline that you can customize to build and deploy your code.
-# Add steps that build, run tests, deploy, and more:
-# https://aka.ms/yaml 
-# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema&viewFallbackFrom=vsts
-# GitHub service connection : https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#sep-github
-
-name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)
-
-variables:
-- group: terraform_test  # variable group
-- name: backend_secret_file_id12
-  value: 'bp1_backend.tfvars'
-- name: main_secret_file_id12
-  value: 'bp1_main.tfvars'
-
-resources:
-  repositories:
-    - repository: terraform # identifier (A-Z, a-z, 0-9, and underscore)
-      type: github
-      endpoint: JamesDLD  # name of the service connection to use (for non-Azure Repos types)
-      name: JamesDLD/terraform
-      
-pool:
-  vmImage: 'Ubuntu-16.04'
-      
-trigger:
-  batch: true
-  branches:
-    include:
-      - master
-      - feature/*
+# Terraform
+parameters:
+  version: ''
+  path: ''
+  ArtifactName: ''
+  backend_secret_file_id: ''
+  main_secret_file_id: ''
+  main_file_path: ''
+  terraform_apply: false
 
 steps:
-
-- checkout: self
-  clean: true
-  persistCredentials: true
-
-- task: DownloadSecureFile@1
-  displayName: 'Download secure file $(backend_secret_file_id12)'
+- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
+  displayName: '${{ parameters.ArtifactName }} - Use Terraform ${{ parameters.version }}'
   inputs:
-    secureFile: $(backend_secret_file_id12)
+    terraformVersion: ${{ parameters.version }}
 
-- task: DownloadSecureFile@1
-  displayName: 'Download secure file $(main_secret_file_id12)'
-  inputs:
-    secureFile: $(main_secret_file_id12)
+- script: |
+    #Action
+    terraform init -backend-config="$(Agent.TempDirectory)/${{ parameters.backend_secret_file_id }}" -reconfigure
 
-- template: pipeline/terraform.yml@terraform
-  parameters:
-    version: $(terraform_version)
-    path: './BestPractice-1/'
-    ArtifactName: 'BestPractice1'
-    backend_secret_file_id: $(backend_secret_file_id12)
-    main_secret_file_id: $(main_secret_file_id12)
-    main_file_path: ''
-    terraform_apply: true
+    if [ "${{ parameters.main_file_path }}" != "" ] ; 
+    then
+      terraform plan -var-file="${{ parameters.main_file_path }}" -var-file="$(Agent.TempDirectory)/${{ parameters.main_secret_file_id }}" -out="./secret/out_plan_file" -input=false -detailed-exitcode > /dev/null
+    else
+      terraform plan -var-file="$(Agent.TempDirectory)/${{ parameters.main_secret_file_id }}" -out="./secret/out_plan_file" -input=false -detailed-exitcode > /dev/null
+    fi
 
-- template: pipeline/terraform.yml@terraform
-  parameters:
-    version: $(terraform_version)
-    path: './BestPractice-2/'
-    ArtifactName: 'BestPractice2'
-    backend_secret_file_id: $(backend_secret_file_id12)
-    main_secret_file_id: $(main_secret_file_id12)
-    main_file_path: './main-jdld.tfvars'
-    terraform_apply: true
+    OUT=$?
+    if [ $OUT -eq 0 ];then
+        echo '##vso[task.setvariable variable=terraform_plan_exitcode]0'
+        echo "${Correct} No changes. Infrastructure is up-to-date!"
+    elif [ $OUT -eq 1 ];then
+        echo '##vso[task.setvariable variable=terraform_plan_exitcode]1'
+        echo "Terraform planned has failed!"
+        exit 1
+    elif [ $OUT -eq 2 ];then
+        echo '##vso[task.setvariable variable=terraform_plan_exitcode]2'
+        echo "${Warning}Changes have been noticed!"
+        terraform show ./secret/out_plan_file
+    else
+        echo "Terraform planned has failed!"
+        exit 1
+    fi
+  displayName: '${{ parameters.ArtifactName }} - Terraform Plan'
+  workingDirectory: ${{ parameters.path }}
 
-- template: pipeline/PublishBuildArtifacts.yml@terraform
-  parameters:
-    ArtifactName: 'BestPractice'
+- script: terraform apply "./secret/out_plan_file"
+  displayName: '${{ parameters.ArtifactName }} - Terraform Apply'
+  workingDirectory: ${{ parameters.path }}
+  condition: and( ${{ parameters.terraform_apply }}, eq(variables['terraform_plan_exitcode'], '2')) # this task will only run if terrafrom has prompted for changes and a terraform apply has been asked
+  
+- script: |
+    echo "Compressing ${{ parameters.path }} directory and move it to ./ArtifactPublishLocation..."
+    tar -czf ${{ parameters.ArtifactName }}.tar.gz -C ${{ parameters.path }} .
+    mkdir ./ArtifactPublishLocation
+    mv -f ${{ parameters.ArtifactName }}.tar.gz ./ArtifactPublishLocation/${{ parameters.ArtifactName }}.tar.gz
+  displayName: '${{ parameters.ArtifactName }} - Compress ${{ parameters.path }} Artifact'
